### ISSUE TITLE
Planning story: eThermostat prototype

### ISSUE THREAD

**Issue by lmas** [lmas/d0020e_code#11]
- [X] Document the use cases (see slide L06.1 pg. 14 and forward for examples)
- [X] Draw a diagram to get an overview of what's required to implement
- [x] Split story into tasks, create issues for each and estimate work time
- [x] Prioritise the tasks and move them around on the kanban board
- Start working on the task with highest priority
- [x] ~Solve #12~
- [x] Solve #4
- [x] Merge the description and diagrams back into ZigBee story

**TODO:**
- How to log power consumption; print message/save in database or file/send to influxdb?
- Eventually this system, or parts of it, should be merged back with the other zigbee system (should be easier to work on a independent system without being affected by other unrelated parts, while working on the hardware issue and tests)

**Use case `#1` description**
Name: `Handle new setPoint value`
Participating actors: `Comfortstat`
Entry condition: `Receives new setPoint from Comfortstat`
Exit condition: `New setPoint stored in memory`
Event flow: 
- Receive new setpoint
- Quickly responds back with an OK to Comfortstat
- Process new setpoint

**Use case `#2` description**
Name: `Continuously monitor temperature/consumption and toggle the power plug accordingly`
Participating actors: `ZigBee device host`
Entry condition: `every x period`
Exit condition: `Plug has been toggled AND/OR consumption has been logged`
Event flow: 
- Start background process and let it run every x period
- For each iteration:
    - Discover temperature system and get current temperature
    - Determine new state of plug, using stored setPoint and temperature
    - If state changed, toggle the plug using API from the ZigBee device host
    - Get latest power consumption
    - Log the data

```mermaid
sequenceDiagram
    participant SR as ServiceRegistrar
    participant OR as Orchestrator
    participant CS as Comfortstat
    participant ET as eThermostat
    participant TP as Temperature
    participant API as ZigBee device host

    loop every x seconds
    ET->>+SR: register
    SR-->>-ET: ok
    end

    loop new setPoint
    CS->>+ET: PUT setPoint
    ET-->>-CS: ok
    end

    loop every x period
    ET->>+OR: GetState(temperature)
    OR->>+SR: Query registry
    SR-->>-OR: System URL
    OR-->>-ET: System URL for temperature

    ET->>+TP: Get temperature
    TP-->>-ET: data

    ET->>+API: Toggle plug (if new state)
    API-->>-ET: ok
    ET->>+API: GET power consumption
    API-->>-ET: data
    end
```

**Comment by lmas** [comment]
Spent about 1h merging this documentation back into the ZigBee story

**Comment by vanDeventer** [comment]
I have to generate a similar sequence diagram for my paper instead of having the picture with the cloud. The current logic is a bit different. 
- All systems register their services with the Service Registrar and re-register them at regular interval (which is specific to the service).
- The service discovery (with the Orchestrator) is done only once and is repeated only if the service becomes unavailable. Since that is a failure, we might not need to have in the sequence diagram.
- The Comtstat should somehow discover the eThermostat.

**Comment by lmas** [comment]
Please note that the diagram here is outdated, there's a better diagram in the ZigBee prototype.

> All systems register their services with the Service Registrar and re-register them at regular interval (which is specific to the service).

Indeed. Would you like to have this shown for the orchestrator and comfortstat too? I was thinking that would make the diagram too busy and so I only showed it for the eThermostat.

> The service discovery (with the Orchestrator) is done only once and is repeated only if the service becomes unavailable. Since that is a failure, we might not need to have in the sequence diagram.

We could show it as a failure state for the "Get temperature from Temperature system"?

> The Comtstat should somehow discover the eThermostat.

No need, this prototype has been merged back into the ZigBee system, which can handle both the smart thermostat and smart plug separately.
